// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPzKrzjeLZ5wTZjKrCSG_2_GvQaevaBgA',
    appId: '1:1002958468780:web:d27093371d16f99ca9d109',
    messagingSenderId: '1002958468780',
    projectId: 'meari-86237',
    authDomain: 'meari-86237.firebaseapp.com',
    storageBucket: 'meari-86237.appspot.com',
    measurementId: 'G-2Z3HNM70RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsWwGXO2IbhBLJ8Jc2Utaqz3yx0WVojnM',
    appId: '1:1002958468780:android:b4a569e6d72c48e2a9d109',
    messagingSenderId: '1002958468780',
    projectId: 'meari-86237',
    storageBucket: 'meari-86237.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkj2C4bDGO4U78k67qR6VzbH1yCs_iAn4',
    appId: '1:1002958468780:ios:c09c2f3cb6fcf9cfa9d109',
    messagingSenderId: '1002958468780',
    projectId: 'meari-86237',
    storageBucket: 'meari-86237.appspot.com',
    iosClientId: '1002958468780-ksa88iclhnh8dmrgebnaa7ito9pu3j5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.meari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkj2C4bDGO4U78k67qR6VzbH1yCs_iAn4',
    appId: '1:1002958468780:ios:c09c2f3cb6fcf9cfa9d109',
    messagingSenderId: '1002958468780',
    projectId: 'meari-86237',
    storageBucket: 'meari-86237.appspot.com',
    iosClientId: '1002958468780-ksa88iclhnh8dmrgebnaa7ito9pu3j5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.meari',
  );
}
